# Generated by Django 4.0.6 on 2025-03-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
